# Generated by Django 5.2 on 2025-05-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='goal',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.PositiveIntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.PositiveIntegerField(default=75),
        ),
    ]
