# Generated by Django 5.2 on 2025-05-19 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_goal_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI tarafından oluşturulan program', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='AI açıklaması veya özel notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('workout', models.TextField(help_text='AI tarafından önerilen antrenman içeriği')),
                ('completed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='users.workoutplan')),
            ],
        ),
    ]
