# Generated by Django 5.2 on 2025-05-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_workoutplan_workoutday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='WorkoutDay',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
