# Generated by Django 5.2 on 2025-05-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
