# Generated by Django 5.2.1 on 2025-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_workoutplan_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=5),
        ),
    ]
